server:
  port: 8080 # 项目启动端口

spring:
  # 只需要改这一个值，就能切换整个环境的配置
  profiles:
    active: dev # 激活哪个环境：dev=本地开发，prod=生产

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ldgen.seckill.controller # 修改为项目中实际的 controller 包名

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-debug: true     # 启用调试器（关键！）
    enable-cache-data: true   # 启用参数缓存（关键！）